
enum BoneIDs
{
	RIGHTFOOT = 24,
	RIGHTKNEECAP = 20,
	RIGHTGROIN = 18,
	RIGHTSHOULDER = 11,
	RIGHTELBOW = 12,
	RIGHTHAND = 13,
	LEFTFOOT = 25,
	LEFTKNEECAP = 21,
	LEFTGROIN = 19,
	LEFTSHOULDER = 15,
	LEFTELBOW = 16,
	LEFTHAND = 17,
	PELVIS = 0,
	UPPERPELVIS = 1,
	STOMACH = 2,
	CHEST = 3,
	UPPERCHEST = 4,
	THROAT = 5,
	CHIN = 6,
	HEAD = 8,
};